namespace LanguageIntegratedQuery.Model {
    internal class ProductList {
        public static readonly List<Product> products = new List<Product>() {
            new Product(1, "Laptop", 999.99m, Category.Electronics),
            new Product(2, "Smartphone", 699.50m, Category.Electronics),
            new Product(3, "Desk Chair", 149.80m, Category.Furniture),
            new Product(4, "Water Bottle", 19.95m, Category.Accessories),
            new Product(5, "Bluetooth Speaker", 59.99m, Category.Electronics),
            new Product(6, "Notebook", 4.99m, Category.Stationery),
            new Product(7, "Pen Set", 9.49m, Category.Stationery),
            new Product(8, "Backpack", 39.99m, Category.Accessories),
            new Product(9, "Running Shoes", 120.00m, Category.Footwear),
            new Product(10, "Coffee Maker", 89.99m, Category.Kitchen),
            new Product(11, "Headphones", 134.25m, Category.Electronics),
            new Product(12, "Table Lamp", 27.99m, Category.Furniture),
            new Product(13, "Yoga Mat", 22.40m, Category.Sports),
            new Product(14, "Sunglasses", 45.00m, Category.Accessories),
            new Product(15, "Wireless Mouse", 25.99m, Category.Electronics),
            new Product(16, "Monitor", 210.89m, Category.Electronics),
            new Product(17, "Keyboard", 49.99m, Category.Electronics),
            new Product(18, "Desk Organizer", 14.59m, Category.Stationery),
            new Product(19, "Electric Kettle", 34.95m, Category.Kitchen),
            new Product(20, "Smartwatch", 199.99m, Category.Electronics),
            new Product(21, "T-Shirt", 18.99m, Category.Clothing),
            new Product(22, "Blender", 65.55m, Category.Kitchen),
            new Product(23, "Book: C# in Depth", 39.99m, Category.Books),
            new Product(24, "Wireless Charger", 29.90m, Category.Electronics),
            new Product(25, "Slippers", 16.80m, Category.Footwear),
            new Product(26, "Flash Drive", 12.99m, Category.Electronics),
            new Product(27, "Action Camera", 299.95m, Category.Electronics),
            new Product(28, "Fitness Tracker", 59.95m, Category.Electronics),
            new Product(29, "Jacket", 89.00m, Category.Clothing),
            new Product(30, "Office Desk", 175.00m, Category.Furniture),
            new Product(31, "Gaming Mouse Pad", 19.99m, Category.Accessories),
            new Product(32, "Toaster", 27.50m, Category.Kitchen),
            new Product(33, "Electric Toothbrush", 44.90m, Category.PersonalCare),
            new Product(34, "Shampoo", 7.80m, Category.PersonalCare),
            new Product(35, "Sneakers", 99.99m, Category.Footwear),
            new Product(36, "Hiking Boots", 140.00m, Category.Footwear),
            new Product(37, "Portable Fan", 23.49m, Category.Electronics),
            new Product(38, "Desk Calendar", 10.50m, Category.Stationery),
            new Product(39, "Digital Camera", 399.00m, Category.Electronics),
            new Product(40, "Cookbook", 24.99m, Category.Books),
            new Product(41, "Throw Blanket", 36.00m, Category.Home),
            new Product(42, "Pillow", 15.99m, Category.Home),
            new Product(43, "Wireless Earbuds", 109.95m, Category.Electronics),
            new Product(44, "Socks (Pack of 5)", 13.99m, Category.Clothing),
            new Product(45, "LED Bulb", 4.49m, Category.Home),
            new Product(46, "Sports Watch", 79.99m, Category.Accessories),
            new Product(47, "Tablet", 249.00m, Category.Electronics),
            new Product(48, "Laptop Stand", 27.99m, Category.Accessories),
            new Product(49, "Tennis Racket", 59.99m, Category.Sports),
            new Product(50, "Desk Fan", 18.75m, Category.Electronics),
        };
    }
}
