namespace LanguageIntegratedQuery.Model {
    internal class SupplierList {
        public static readonly List<Supplier> suppliers = new List<Supplier>()
        {
            new Supplier(1, "Global Electronics", 1),
            new Supplier(2, "Tech World", 2),
            new Supplier(3, "Office Comforts", 3),
            new Supplier(4, "Hydrate Supplies", 4),
            new Supplier(5, "Sound Hub", 5),
            new Supplier(6, "Paper Co.", 6),
            new Supplier(7, "Inkwell", 7),
            new Supplier(8, "Urban Gear", 8),
            new Supplier(9, "SportsMax", 9),
            new Supplier(10, "KitchenPro", 10),
            new Supplier(11, "AudioWave", 11),
            new Supplier(12, "BrightHome", 12),
            new Supplier(13, "YogaLife", 13),
            new Supplier(14, "SunShades", 14),
            new Supplier(15, "ClickTech", 15),
            new Supplier(16, "Vision Displays", 16),
            new Supplier(17, "Boardroom Supplies", 17),
            new Supplier(18, "Workspace Solutions", 18),
            new Supplier(19, "KitchenPro", 19),
            new Supplier(20, "Tech World", 20),
            new Supplier(21, "Urban Gear", 21),
            new Supplier(22, "KitchenPro", 22),
            new Supplier(23, "BookWorld", 23),
            new Supplier(24, "PowerUp", 24),
            new Supplier(25, "FootWorks", 25),
            new Supplier(26, "Storage Solutions", 26),
            new Supplier(27, "PhotoTech", 27),
            new Supplier(28, "FitGear", 28),
            new Supplier(29, "Urban Gear", 29),
            new Supplier(30, "Office Comforts", 30),
            new Supplier(31, "GameZone", 31),
            new Supplier(32, "KitchenPro", 32),
            new Supplier(33, "CarePlus", 33),
            new Supplier(34, "CarePlus", 34),
            new Supplier(35, "FootWorks", 35),
            new Supplier(36, "SportsMax", 36),
            new Supplier(37, "CoolTech", 37),
            new Supplier(38, "Paper Co.", 38),
            new Supplier(39, "PhotoTech", 39),
            new Supplier(40, "BookWorld", 40),
            new Supplier(41, "HomeEssentials", 41),
            new Supplier(42, "HomeEssentials", 42),
            new Supplier(43, "AudioWave", 43),
            new Supplier(44, "Urban Gear", 44),
            new Supplier(45, "BrightHome", 45),
            new Supplier(46, "Urban Gear", 46),
            new Supplier(47, "Tech World", 47),
            new Supplier(48, "Workspace Solutions", 48),
            new Supplier(49, "SportsMax", 49),
            new Supplier(50, "CoolTech", 50),
        };
    }
}
